ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseurl = "/"
title = "rsantana"

theme = "hugo-coder"

languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Raildo Santana"
    description = "Projects"
    keywords = "blog,developer,personal"
    info = "Data Analyst and Cooker"
    avatarurl = "images/perfil.jpg"
    footercontent = "Making with love <3."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/raildosantana"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@johndoe"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.pt-br]
        languagename = "PortuguÃªs"
        title = "Raildo Santana"

        [languages.pt-br.params]
            author = "Raildo Santana"
            info = "Analista de Dados e Cozinheiro"
            description = "Projetos"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "Feito com amor <3."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "contact/"
